os:
- osx
- linux
osx_image: xcode7.2
env:
  - NODE_VERSION="0.10"
  - NODE_VERSION="0.12"
  - NODE_VERSION="4"
  - NODE_VERSION="5"
matrix:
  fast_finish: true
  include:
    - os: osx
      env: NODE_VERSION="5" NVM_DIR=~/.nvm
    - os: linux
      env: NODE_VERSION="5" BROWSER_TESTS=1 SAUCE_USERNAME=testem-ci SAUCE_ACCESS_KEY=1f00979e-0252-4d69-98ff-f6c85d1a746b
  exclude:
    - os: osx
sudo: false
before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew update;
      brew install phantomjs nvm;
      mkdir ~/.nvm;
      . $(brew --prefix nvm)/nvm.sh;
    fi
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - node --version
  - npm --version
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm run test
  - npm run integration
