os:
- osx
- linux
osx_image: xcode7.2
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
matrix:
  fast_finish: true
  include:
    - os: osx
      node_js: "5"
    - os: linux
      node_js: "5"
      env: BROWSER_TESTS=1 SAUCE_USERNAME=testem-ci SAUCE_ACCESS_KEY=1f00979e-0252-4d69-98ff-f6c85d1a746b
  exclude:
    - os: osx
sudo: false
before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew update;
      brew install phantomjs;
    fi
  - npm config set spin false
install:
  - travis_retry npm install
before_script:
  - npm run lint
script:
  - npm run test
  - npm run integration
