language: node_js
node_js:
- '0.12'
- '0.10'
- iojs
matrix:
  fast_finish: true
sudo: false
deploy:
  provider: npm
  email: johannes.wuerbach@googlemail.com
  api_key:
    secure: bmOEDf2yE8tmjuFQaDOHNnHkANi0nKaaOVbvnHNNUUMHOVttGSCQCD/lg/AZOQoedigwtUPzbL06xEvjr9SIKjETkpzu2nEms8qACqps14q55K61Luz6Gjyy22u6sXVG5H7JMihzM5H4ZFYqP1gbN6h7BequtCT7B96xFzEpDF4=
  on:
    tags: true
    repo: airportyh/testem
    node: iojs
